import type { Metadata } from 'next';
import localFont from 'next/font/local';
import SchemeProvider from '@/components/providers/SchemeProvider';
import RandomThemeProvider from '@/components/providers/RandomThemeProvider';
import './globals.css';

const ppNeueMontreal = localFont({
  src: [
    {
      path: './fonts/ppneuemontreal-thin.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './fonts/ppneuemontreal-book.otf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './fonts/ppneuemontreal-medium.otf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './fonts/ppneuemontreal-bold.otf',
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-ppNeueMontreal',
});

export const metadata: Metadata = {
  title: 'Felipe Saracho',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={`${ppNeueMontreal.variable} h-screen flex text-foreground bg-background font-neue antialiased md:transition-colors`}
      >
        <SchemeProvider
          attribute='class'
          defaultTheme='system'
          enableSystem
        >
          <RandomThemeProvider>{children}</RandomThemeProvider>
        </SchemeProvider>
      </body>
    </html>
  );
}
