import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const getFontPath = (weight: string = 'medium'): string => {
  return `./fonts/ppneuemontreal-${weight}.otf`;
};

const ppNeueMontreal = localFont({
  src: [
    {
      path: getFontPath('thin'),
      weight: '400',
      style: 'normal',
    },
    {
      path: getFontPath('normal'),
      weight: '500',
      style: 'normal',
    },
    {
      path: getFontPath('book'),
      weight: '600',
      style: 'normal',
    },
    {
      path: getFontPath('bold'),
      weight: '700',
      style: 'normal',
    },
  ],
  display: 'swap',
  variable: '--font-ppNeueMontreal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${ppNeueMontreal.variable} font-neue antialiased`}>
        {children}
      </body>
    </html>
  );
}
